# Use the official Node.js image as base
FROM node:18.19.0
WORKDIR /app

COPY package*.json ./
RUN npm install
COPY src ./src

COPY prisma ./prisma
RUN npx prisma generate  

EXPOSE 8080
CMD npm run dev